version: '2.0'
services:
  web:
    build: .
    ports:
      - '8000:8000'
    links:
      - postgresql
      - redis
      - worker
      - elasticsearch
    environment:
      PORT: 8000
    env_file:
      - dev.env
    command:
      - /bin/bash
      - '-c'
      - |
        python manage.py migrate --settings=yafig_api.settings.dev
        python manage.py runserver 0.0.0.0:8000 --settings=yafig_api.settings.dev
    volumes:
      - './:/app'
  worker:
    build: .
    links:
      - postgresql
      - redis
      - elasticsearch
    env_file:
      - dev.env
    command:
      - /bin/bash
      - '-c'
      - |
        celery -A yafig_api worker -l debug
    volumes:
      - './:/app'
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: yafig
  redis:
    image: redis
  elasticsearch:
          image: elasticsearch:6.8.10
  flower:
    build: .
    ports:
      - 5555:5555
    links:
      - postgresql
      - redis
      - elasticsearch
    env_file:
      - dev.env
    command:
      - /bin/bash
      - '-c'
      - |
        celery flower -A yafig_api worker -l debug --address=0.0.0.0 --port=5555
    volumes:
      - './:/app'