version: '2.0'
services:
  web:
    build: .
    ports:
      - '8000:8000'
    links:
      - postgresql
      - redis
      - celery
      - elasticsearch
    environment:
      PORT: 8000
    env_file:
      - dev.env
    command:
      - /bin/bash
      - '-c'
      - |
        python manage.py migrate --settings=yafig_api.settings.dev
        python manage.py runserver 0.0.0.0:8000 --settings=yafig_api.settings.dev
    volumes:
      - './:/app'
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: yafig
  redis:
    image: redis
  celery:
    image: celery
  elasticsearch:
          image: elasticsearch:6.8.10
