# Generated by Django 3.0.6 on 2020-05-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200502_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=120),
        ),
    ]
