# Generated by Django 3.1 on 2020-09-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_timeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_by',
            new_name='created_by',
        ),
    ]
