# Generated by Django 3.1 on 2020-09-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200903_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_by',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_at',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted_at',
            new_name='created_at',
        ),
    ]
